[package]
name = "my-relly"
version = "0.1.0"
authors = ["tani <13175394+utnkw@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "1.0"